### ISSUE TITLE
Upgrade to Node 8 breaks plugin

### ISSUE THREAD

**Issue by wernerglinka** [wernerglinka/metalsmith-prism#23]
After upgrading node to version 8 my build process breaks. 
```
TypeError: Cannot read property 'tokenizePlaceholders' of undefined
    at /Users/.../node_modules/prismjs/components/prism-php.js:121:40
    at Object.run (/Users/.../node_modules/prismjs/prism.js:456:5)
    at Object.highlight (/Users/.../node_modules/prismjs/prism.js:287:11)
    at Object.<anonymous> (/Users/.../node_modules/metalsmith-prism/lib/index.js:94:41)
    at initialize.exports.each (/Users/.../node_modules/cheerio/lib/api/traversing.js:300:24)
    at _.each (/Users/.../node_modules/metalsmith-prism/lib/index.js:62:17)
    at /Users/.../node_modules/metalsmith-prism/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/Users/.../node_modules/metalsmith-prism/node_modules/lodash/lodash.js:3002:24)
    at /Users/.../node_modules/metalsmith-prism/node_modules/lodash/lodash.js:4886:18
    at Function.forEach (/Users/.../node_modules/metalsmith-prism/node_modules/lodash/lodash.js:9334:14)
    at Ware.<anonymous> (/Users/.../node_modules/metalsmith-prism/lib/index.js:51:7)
    at Ware.<anonymous> (/Users/.../node_modules/wrap-fn/index.js:45:19)
    at next (/Users/.../node_modules/ware/lib/index.js:85:20)
    at /Users/.../node_modules/wrap-fn/index.js:121:18
    at /Users/.../node_modules/metalsmith-in-place/node_modules/async/lib/async.js:52:16
    at done (/Users/.../node_modules/metalsmith-in-place/node_modules/async/lib/async.js:246:17)
```

Any idea what this could be? Any pointer is appreciated.

**Comment by robmcguinness** [comment]
I think this is related to:

- https://github.com/PrismJS/prism/issues/1395
- https://github.com/PrismJS/prism/issues/1400

**Comment by wernerglinka** [comment]
Yes, I have found those but how do I deal with this at this plugin level?

**Comment by robmcguinness** [comment]
Have you tried: https://github.com/Availity/metalsmith-prism#preload-optional

**Comment by robmcguinness** [comment]
Let me know if that helps.

**Comment by robmcguinness** [comment]
Example fix for `php` syntax: https://github.com/PrismJS/prism/issues/1400#issuecomment-382688112 or https://github.com/PrismJS/prism/pull/1359
